[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "etas-toolkit"
version = "0.1.0"
description = "A Python library for Epidemic-Type Aftershock Sequence (ETAS) earthquake forecasting."
readme = "README.md"
authors = [
    {name = "Devansh Verma"}
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "pyarrow",
    "scikit-learn",
    "obspy",
    "pyproj",
    "cartopy",
    "pygmt",
    "networkx",
    "matplotlib",
    "jupyterlab",
    "ipykernel",
    "pytest",
    "seismostats"
]

[project.optional-dependencies]
test = [
    "pytest"
]
